site_name: Q_C Notebook
copyright: Copyright &copy; 2024 <a href="https://github.com/Fu-Qingchen" target="_blank" rel="noopener">Fu_Qingchen</a>  <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener">鄂ICP备2023023991号-1</a> <img src="https://beian.mps.gov.cn/web/assets/logo01.6189a29f.png" alt="img" style="zoom:20%;" /> <a href="https://beian.mps.gov.cn/#/query/webSearch?code=42018502007065" rel=\"noreferrer\" target=\"_blank\">鄂公网安备42018502007065</a>

theme: 
  name: 'material'
  language: zh
  favicon: assets/book.svg
  icon: 
    logo: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  font: false
  palette:
    # - scheme: default
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  # - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - css/jetbrainsmono.css
  - css/katex.min.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/changelog_extra.css
  - css/heti.css

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search:
      lang: en
  - tags